import type { CountryRankingRow, PredictionHistoryRow, UpcomingPredictionRow } from "@/contracts";

export const MOCK_COUNTRY_RANKINGS: CountryRankingRow[] = [
  {
    rank: 1,
    country_name: "Spain",
    country_uid: "C_ES",
    elo_rating: 1850,
    attack_rating: 91,
    defense_rating: 88,
    recent_form_score: 0.86,
    squad_overall_strength: 89,
    momentum_score: 0.12,
    consistency_score: 0.84,
    confederation: "UEFA",
  },
  {
    rank: 2,
    country_name: "Brazil",
    country_uid: "C_BR",
    elo_rating: 1820,
    attack_rating: 90,
    defense_rating: 84,
    recent_form_score: 0.82,
    squad_overall_strength: 88,
    momentum_score: 0.08,
    consistency_score: 0.8,
    confederation: "CONMEBOL",
  },
  {
    rank: 3,
    country_name: "Argentina",
    country_uid: "C_AR",
    elo_rating: 1800,
    attack_rating: 88,
    defense_rating: 86,
    recent_form_score: 0.8,
    squad_overall_strength: 87,
    momentum_score: 0.06,
    consistency_score: 0.79,
    confederation: "CONMEBOL",
  },
  {
    rank: 4,
    country_name: "France",
    country_uid: "C_FR",
    elo_rating: 1790,
    attack_rating: 89,
    defense_rating: 85,
    recent_form_score: 0.79,
    squad_overall_strength: 86,
    momentum_score: 0.04,
    consistency_score: 0.77,
    confederation: "UEFA",
  },
  {
    rank: 5,
    country_name: "Germany",
    country_uid: "C_DE",
    elo_rating: 1760,
    attack_rating: 86,
    defense_rating: 83,
    recent_form_score: 0.76,
    squad_overall_strength: 84,
    momentum_score: -0.01,
    consistency_score: 0.75,
    confederation: "UEFA",
  },
];

export const MOCK_PREDICTION_HISTORY: PredictionHistoryRow[] = [
  {
    timestamp: "2026-05-21T12:00:00Z",
    match: "Spain vs Germany",
    predicted_score: "2-1",
    confidence: 68,
    home_win_pct: 62,
    draw_pct: 18,
    away_win_pct: 20,
  },
  {
    timestamp: "2026-05-21T11:30:00Z",
    match: "Brazil vs Argentina",
    predicted_score: "1-1",
    confidence: 64,
    home_win_pct: 48,
    draw_pct: 26,
    away_win_pct: 26,
  },
  {
    timestamp: "2026-05-21T11:00:00Z",
    match: "France vs England",
    predicted_score: "2-0",
    confidence: 61,
    home_win_pct: 54,
    draw_pct: 22,
    away_win_pct: 24,
  },
];

export const MOCK_UPCOMING_PREDICTIONS: UpcomingPredictionRow[] = [
  { match: "Spain vs Germany", home_win: "62%", draw: "18%", away_win: "20%" },
  { match: "Brazil vs Argentina", home_win: "48%", draw: "22%", away_win: "30%" },
  { match: "France vs England", home_win: "54%", draw: "20%", away_win: "26%" },
];
